<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'PayumDoctrineORMModule\Module'                => __DIR__ . '/Module.php',
  'PayumDoctrineORMModule\Entity\PaymentDetails' => __DIR__ . '/src/PayumDoctrineORMModule/Entity/PaymentDetails.php',
  'PayumDoctrineORMModule\Entity\Token'          => __DIR__ . '/src/PayumDoctrineORMModule/Entity/Token.php',
);
